"""ADD USER PHONE NUMBER COLUMN

Revision ID: 4bebed7dd25b
Revises: a12a35e52b52
Create Date: 2023-12-17 19:15:52.217301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bebed7dd25b'
down_revision: Union[str, None] = 'a12a35e52b52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phoneNumber', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phoneNumber')
    # ### end Alembic commands ###
